/**
 * Content Generation Service
 * Сервис для создания содержимого Markdown документации
 */

import { type } from 'os';
import type {
  ProjectScanResult,
  PageScanResult,
  LayoutScanResult,
  ComponentNode,
  TailwindConfigScanResult,
} from '../types/scanner.js';
import { ComponentAnalysisService } from './component-analysis.service.js';
import { MarkdownFormattingService } from './markdown-formatting.service.js';

/**
 * Сервис генерации контента Markdown
 */
export class ContentGenerationService {
  private readonly analysisService: ComponentAnalysisService;
  private readonly formattingService: MarkdownFormattingService;

  constructor(verbose: boolean) {
    this.analysisService = new ComponentAnalysisService(verbose);
    this.formattingService = new MarkdownFormattingService(verbose);
  }

  /**
   * Создание Markdown контента для компонента (секции или топ-левел)
   */
  createComponentMarkdown(component: ComponentNode, pagePath: string): string {
    // Получаем ВСЕ вложенные компоненты этого компонента
    const allNestedComponents = this.analysisService.flattenComponents([component]);
    const nestedOnly = allNestedComponents.filter(comp => comp !== component);

    // Проверяем наличие динамических классов во ВСЕХ компонентах
    const hasDynamicClasses = allNestedComponents.some(
      comp => comp.styles.dynamicClasses && comp.styles.dynamicClasses.length > 0
    );

    return `# ${component.name}

**File**: \`${component.filePath}\`  
**Page**: \`${pagePath}\`  
**Generated**: ${new Date().toISOString()}

---

## 📋 Component Summary

* **Direct Children**: ${component.children.length}
* **Total Nested Components**: ${nestedOnly.length}
* **Max Nesting Depth**: ${this.analysisService.getMaxDepth(allNestedComponents)} levels
* **Dynamic Classes Detected**: ${hasDynamicClasses ? '✅' : '❌'}
* **Named Imports**: ${(() => {
      return component.imports.map(imp => imp.name).join(', ') || 'None';
    })()}
* **Named Exports**: ${component.exports.map(exp => exp.name).join(', ') || 'None'}

---

## 🧩 Component Tree

\`\`\`
${this.formattingService.renderComponentTreeText(allNestedComponents)}
\`\`\`

---

## 🎨 Styles Per Component

${this.formattingService.renderDetailedComponentStyles(allNestedComponents)}

---

## 🔍 Complete Tailwind Summary

${this.formattingService.renderTailwindSummaryByComponent(allNestedComponents)}

---

*Generated by @repo/style-scanner*
`;
  }

  /**
   * Создание сводного Markdown файла
   */
  createSummaryMarkdown(projectResult: ProjectScanResult): string {
    const { summary, pages, tailwindConfigs } = projectResult;
    return `# Style Scanner - Project Summary

Generated: ${new Date().toISOString()}

## 📊 Overview

- **Total Pages Scanned**: ${summary.totalPages}
- **Total Layouts Scanned**: ${summary.totalLayouts}
- **Total UI Components Scanned**: ${summary.totalUIComponents}
- **Total Tailwind Configs Scanned**: ${summary.totalTailwindConfigs || 0}
- **Total Components Found**: ${summary.totalComponents}
- **Total Errors**: ${summary.totalErrors}
- **Total Config Issues**: ${summary.totalConfigIssues || 0}
- **Scan Duration**: ${summary.scanDuration}ms

${tailwindConfigs && tailwindConfigs.length > 0 ? this.createTailwindConfigSection(tailwindConfigs) : ''}

## 📄 Pages Analysis

${pages
  .map(page => {
    const { projectName, pageName } = this.extractProjectAndPageNames(page.pagePath);
    return `
### ${this.formattingService.formatPagePath(page.pagePath)}

- **Components**: ${page.components.length}
- **Errors**: ${page.errors.length}
- **Project**: [\`${projectName}\`](./${projectName}/${pageName}/overview.md)
- **Sections**: ${
      page.components
        .filter(c => c.depth === 0)
        .map(
          comp =>
            `[\`${comp.name}\`](./${projectName}/${pageName}/${this.formattingService.sanitizeFileName(comp.name)}.md)`
        )
        .join(', ') || '_No sections_'
    }
`;
  })
  .join('\n')}

---

*Generated by @repo/style-scanner*
`;
  }

  /**
   * Создание overview Markdown для страницы
   */
  createPageOverviewMarkdown(
    pageResult: PageScanResult,
    projectName: string,
    pageName: string
  ): string {
    const { pagePath, components, errors } = pageResult;
    return `# ${projectName} - ${pageName}

**File**: \`${pagePath}\`  
**Generated**: ${new Date().toISOString()}

## 📊 Overview

- **Total Components**: ${components.length}
- **Top-level Components**: ${components.filter(c => c.depth === 0).length}
- **Errors**: ${errors.length}

## 🧩 Top-level Components

${components
  .filter(c => c.depth === 0)
  .map(comp => {
    const styleCount =
      comp.styles.tailwind.length + comp.styles.cssModules.length + comp.styles.cssInJs.length;
    return `- **[${comp.name}](./${this.formattingService.sanitizeFileName(comp.name)}.md)** (${styleCount} styles) - \`${comp.filePath}\``;
  })
  .join('\n')}

---

*Generated by @repo/style-scanner*
`;
  }

  /**
   * Создание overview Markdown для layout
   */
  createLayoutOverviewMarkdown(
    layoutResult: LayoutScanResult,
    projectName: string,
    layoutName: string
  ): string {
    const { layoutPath, layoutType, components, errors } = layoutResult;
    return `# ${projectName} - ${layoutName} Layout

**File**: \`${layoutPath}\`  
**Type**: \`${layoutType}\`  
**Generated**: ${new Date().toISOString()}

## 📊 Overview

- **Total Components**: ${components.length}
- **Layout Type**: ${layoutType}
- **Errors**: ${errors.length}

## 🧩 Layout Components

${
  components.length > 0
    ? components
        .map(comp => {
          const styleCount =
            comp.styles.tailwind.length +
            comp.styles.cssModules.length +
            comp.styles.cssInJs.length;
          return `- **[${comp.name}](./${this.formattingService.sanitizeFileName(comp.name)}.md)** (${styleCount} styles) - \`${comp.filePath}\``;
        })
        .join('\n')
    : '_No components found_'
}

---

*Generated by @repo/style-scanner*
`;
  }

  /**
   * Извлечение имени проекта и страницы из пути (дублирует логику для совместимости)
   */
  private extractProjectAndPageNames(pagePath: string): { projectName: string; pageName: string } {
    const normalizedPath = pagePath.replace(/\\/g, '/');
    const pathParts = normalizedPath.split('/');
    let projectName = 'unknown';
    let pageName = 'page';

    const appsIndex = pathParts.findIndex(part => part === 'apps');
    if (appsIndex !== -1 && pathParts[appsIndex + 1]) {
      projectName = pathParts[appsIndex + 1] || 'unknown';
    }

    const appIndex = pathParts.findIndex(part => part === 'app');
    if (appIndex !== -1) {
      const pageStructure = pathParts.slice(appIndex + 1, -1);
      if (pageStructure.length === 0) {
        pageName = 'home-page';
      } else if (pageStructure.includes('[locale]')) {
        const filteredParts = pageStructure.filter(part => !part.startsWith('['));
        pageName = filteredParts.length > 0 ? filteredParts.join('-') + '-page' : 'home-page';
      } else {
        pageName = pageStructure.join('-') + '-page';
      }
    }

    return { projectName, pageName };
  }
  /**
   * Создание секции Tailwind Configuration Analysis
   */
  private createTailwindConfigSection(
    tailwindConfigs: readonly TailwindConfigScanResult[]
  ): string {
    const totalIssues = tailwindConfigs.reduce((sum, config) => sum + config.issues.length, 0);
    const totalErrors = tailwindConfigs.reduce((sum, config) => sum + config.errors.length, 0);

    let section = `## ⚙️ Tailwind Configuration Analysis

- **Total Configurations**: ${tailwindConfigs.length}
- **Total Issues Found**: ${totalIssues}
- **Total Errors**: ${totalErrors}

`;

    if (tailwindConfigs.length === 0) {
      section += '_No Tailwind configurations found._\n\n';
      return section;
    }

    // Группируем по типам конфигураций
    const configsByType = {
      root: tailwindConfigs.filter(c => c.configType === 'root'),
      'app-specific': tailwindConfigs.filter(c => c.configType === 'app-specific'),
      preset: tailwindConfigs.filter(c => c.configType === 'preset'),
    };

    for (const [type, configs] of Object.entries(configsByType)) {
      if (configs.length === 0) continue;

      section += `### ${type.charAt(0).toUpperCase() + type.slice(1)} Configurations\n\n`;

      for (const config of configs) {
        const issuesByType = this.groupIssuesByType(config.issues);
        const hasIssues = config.issues.length > 0;
        const hasErrors = config.errors.length > 0;

        section += `#### \`${config.configPath}\`\n\n`;
        section += `- **Type**: ${config.configType}\n`;
        section += `- **Content Paths**: ${config.stats.totalContentPaths}\n`;
        section += `- **Valid Paths**: ${config.stats.validPaths}\n`;
        section += `- **Issues**: ${config.issues.length}\n`;
        section += `- **Errors**: ${config.errors.length}\n\n`;

        if (hasErrors) {
          section += `**❌ Errors:**\n`;
          for (const error of config.errors) {
            section += `- ${error.type}: ${error.message}\n`;
          }
          section += '\n';
        }

        if (hasIssues) {
          section += `**⚠️ Issues Found:**\n\n`;

          for (const [issueType, issues] of Object.entries(issuesByType)) {
            if (issues.length === 0) continue;

            section += `**${this.formatIssueType(issueType)}** (${issues.length}):\n`;
            for (const issue of issues) {
              const severityIcon = this.getSeverityIcon(issue.severity);
              section += `- ${severityIcon} ${issue.message}\n`;
              if (issue.path) {
                section += `  - Path: \`${issue.path}\`\n`;
              }
              if (issue.suggestion) {
                section += `  - 💡 Suggestion: ${issue.suggestion}\n`;
              }
            }
            section += '\n';
          }
        }

        if (!hasIssues && !hasErrors) {
          section += `✅ _No issues found in this configuration._\n\n`;
        }
      }
    }

    return section;
  }

  /**
   * Группировка issues по типам
   */
  private groupIssuesByType(issues: readonly any[]): Record<string, any[]> {
    return issues.reduce(
      (groups, issue) => {
        const type = issue.type || 'unknown';
        if (!groups[type]) {
          groups[type] = [];
        }
        groups[type].push(issue);
        return groups;
      },
      {} as Record<string, any[]>
    );
  }

  /**
   * Форматирование типа issue для отображения
   */
  private formatIssueType(type: string): string {
    const typeMap: Record<string, string> = {
      dead_path: 'Dead Paths',
      empty_glob: 'Empty Glob Patterns',
      missing_file: 'Missing Files',
      redundant_path: 'Redundant Paths',
      inefficient_glob: 'Inefficient Glob Patterns',
    };
    return typeMap[type] || type.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  }

  /**
   * Получение иконки для уровня серьезности
   */
  private getSeverityIcon(severity: string): string {
    const iconMap: Record<string, string> = {
      error: '🔴',
      warning: '🟡',
      info: '🔵',
    };
    return iconMap[severity] || '⚪';
  }
}
